Repository Marquinho1775/BMT-PI, pull requests merged in 2024-11, with the labels that each got.

#50 Unit Test David
  backend/BMT-backend/BMT-UnitTesting/TokenServicesTest.cs
Labels: enhancement

#52 3 Unit testings de Marco Angulo
  backend/BMT-backend/BMT-UnitTesting/MailManagerTest.cs
Labels: documentation

#54 Bug fix: Se corrige la modificación de direcciones.
  frontend/bmt-frontend/src/components/UserProfilePage.vue
Labels: bug

#55 Tarjetas de crédito nuevas
  frontend/bmt-frontend/src/components/CheckOut.vue
  frontend/bmt-frontend/src/components/UserCardForm.vue
  frontend/bmt-frontend/src/components/UserProfilePage.vue
Labels: enhancement, good first issue

#56 Mostrar datos faltantes en la card de cada producto.
  frontend/bmt-frontend/src/components/CheckOut.vue
  frontend/bmt-frontend/src/components/ProductCard.vue
  frontend/bmt-frontend/src/components/UserProfilePage.vue
Labels: enhancement

#58 Creado proyecto de tests funcional nuevo
  backend/BMT-Unit-Tests/BMT-Unit-Tests.csproj
  backend/BMT-Unit-Tests/ShoppingCartServiceTest.cs
  backend/BMT-Unit-Tests/UnitTest1.cs
  backend/BMT-backend/BMT-backend.sln
Labels: enhancement

#60 Correcciones brandon sprint3
  backend/BMT-backend/Application/Interfaces/IEnterpriseRepository.cs
  backend/BMT-backend/Application/Interfaces/IImageFileService.cs
  backend/BMT-backend/Application/Interfaces/IProductRepository.cs
  backend/BMT-backend/Application/Interfaces/ITagRepository.cs
  backend/BMT-backend/Application/Queries/SearchProductsAndEnterprisesQuerie.cs
  backend/BMT-backend/Application/Services/ProductService.cs
  backend/BMT-backend/Application/Services/TagService.cs
  backend/BMT-backend/BMT-backend.csproj
  backend/BMT-backend/Infrastructure/Data/EnterpriseRepository.cs
  backend/BMT-backend/Infrastructure/Data/ProductRepository.cs
  backend/BMT-backend/Infrastructure/Data/ShoppingCartRepository.cs
  backend/BMT-backend/Infrastructure/Data/TagRepository.cs
  backend/BMT-backend/Infrastructure/ImageFileService.cs
  backend/BMT-backend/Presentation/Controllers/DeveloperController.cs
  backend/BMT-backend/Presentation/Controllers/SearchController.cs
  backend/BMT-backend/Presentation/Controllers/ShoppingCartController.cs
  backend/BMT-backend/Presentation/Controllers/TagController.cs
  backend/BMT-backend/Presentation/DTOs/SearchProductsAndEntperisesDto.cs
  backend/BMT-backend/Program.cs
  backend/BMT-backend/wwwroot/uploads/07f0849c-bc4c-401f-8890-a08a323acbe1.jpg
  backend/BMT-backend/wwwroot/uploads/1adbb276-cd38-42a5-8549-277114e11b79.jpg
  backend/BMT-backend/wwwroot/uploads/2586afd3-d685-4157-9038-d22d60afee14.jpg
  backend/BMT-backend/wwwroot/uploads/2e9c3dea-2cc7-41dc-8a30-20a937add6ef.jpg
  backend/BMT-backend/wwwroot/uploads/3025923d-cae8-4a00-ab67-6779bffe4b1c.jpg
  backend/BMT-backend/wwwroot/uploads/40428396-b223-4f55-b635-39baf88500de.jpg
  backend/BMT-backend/wwwroot/uploads/415dfb73-237d-498c-b375-d7945078f565.jpg
  backend/BMT-backend/wwwroot/uploads/4647ff12-ed1f-4200-9e34-46df5b598cbb.jpg
  backend/BMT-backend/wwwroot/uploads/4b9ec414-2d09-4753-b42d-6a6ef6d0ff6f.jpeg
  backend/BMT-backend/wwwroot/uploads/69470f67-815d-4b15-a128-e8f9601d8c74.jpg
  backend/BMT-backend/wwwroot/uploads/69894292-db49-4a41-9c65-685f277f4c37.jpg
  backend/BMT-backend/wwwroot/uploads/71464464-0371-4f45-8700-561d03236fba.jpg
  backend/BMT-backend/wwwroot/uploads/76312787-b507-4488-8c85-8be86717d70a.jpg
  backend/BMT-backend/wwwroot/uploads/7e84c631-bee8-4c04-b1cf-75a8609aaae3.jpg
  backend/BMT-backend/wwwroot/uploads/8306936a-06e3-4237-b9a8-2930efed027c.jpg
  backend/BMT-backend/wwwroot/uploads/84eaea79-0b69-45f8-9142-4620d1461196.jpg
  backend/BMT-backend/wwwroot/uploads/9fc2a1ba-e0e8-4009-9678-dbfa15b0c5e2.jpg
  backend/BMT-backend/wwwroot/uploads/a09e4693-9349-468e-88f2-25d66e84279d.jpg
  backend/BMT-backend/wwwroot/uploads/a2d4fdcf-5bb2-4843-bf1e-b9c7a401cce3.jpg
  backend/BMT-backend/wwwroot/uploads/a4c18c7a-e456-4849-bee2-a330fd879fdf.jpg
  backend/BMT-backend/wwwroot/uploads/a9d8f23d-9e57-4b4b-bcc5-7bbd66b9c4de.jpg
  backend/BMT-backend/wwwroot/uploads/ac3d1129-dbbd-4b9d-97f0-516341ee5896.jpg
  backend/BMT-backend/wwwroot/uploads/b22af0de-d158-400f-9efe-d8b24486d00b.jpg
  backend/BMT-backend/wwwroot/uploads/bfbd252b-e878-493a-86fe-fb473fee3d51.jpg
  backend/BMT-backend/wwwroot/uploads/c7b463fb-1ec4-41de-ba0a-af569caeb7b8.jpg
  backend/BMT-backend/wwwroot/uploads/cae3b4cc-62bc-4d51-99df-9b007ef5e0f4.jpg
  frontend/bmt-frontend/src/components/AppHeader.vue
  frontend/bmt-frontend/src/components/EditEnterpriseInfo.vue
  frontend/bmt-frontend/src/components/EnterpriseInventory.vue
  frontend/bmt-frontend/src/components/HomePage.vue
  frontend/bmt-frontend/src/components/ProductCard.vue
  frontend/bmt-frontend/src/components/ProductGrid.vue
  frontend/bmt-frontend/src/components/ProductRegisterForm.vue
  frontend/bmt-frontend/src/components/ProductSearchGrid.vue
  frontend/bmt-frontend/src/components/SearchResultPage.vue
  frontend/bmt-frontend/src/main.js
Labels: enhancement

#62 Funcionalidad completa para la exportación a PDF
  frontend/bmt-frontend/package-lock.json
  frontend/bmt-frontend/package.json
  frontend/bmt-frontend/src/components/HomePage.vue
  frontend/bmt-frontend/src/components/YearlyEarnings.vue
Labels: enhancement

#63 Reportes pedidos pendientes
  backend/BMT-backend/Application/Services/OrderService.cs
  backend/BMT-backend/Infrastructure/Data/OrderRepository.cs
  frontend/bmt-frontend/src/components/AppSidebar.vue
  frontend/bmt-frontend/src/components/HomePage.vue
  frontend/bmt-frontend/src/components/OrdersReports.vue
  frontend/bmt-frontend/src/components/ReportsDashboard.vue
  frontend/bmt-frontend/src/components/ReportsTable.vue
  frontend/bmt-frontend/src/main.js
Labels: enhancement

#64 Client dashboard
  backend/BMT-backend/Application/Interfaces/IOrderRepository.cs
  backend/BMT-backend/Application/Services/OrderService.cs
  backend/BMT-backend/Infrastructure/Data/OrderRepository.cs
  backend/BMT-backend/Presentation/Controllers/UserController.cs
  frontend/bmt-frontend/src/components/HomePage.vue
  frontend/bmt-frontend/src/components/ProductCard.vue
  frontend/bmt-frontend/src/components/UserDashboard.vue
  frontend/bmt-frontend/src/main.js
Labels: documentation, enhancement, good first issue, question

#67 Fix
  backend/BMT-Unit-Tests/DirectionServiceTest.cs
  backend/BMT-Unit-Tests/EnterpriseServiceTest.cs
  backend/BMT-Unit-Tests/OrderServiceTest.cs
  backend/BMT-Unit-Tests/ProductServiceTest.cs
  backend/BMT-Unit-Tests/UserServiceTest.cs
  backend/BMT-backend/Application/Interfaces/IDirectionRepository.cs
  backend/BMT-backend/Application/Interfaces/IEnterpriseRepository.cs
  backend/BMT-backend/Application/Interfaces/IOrderRepository.cs
  backend/BMT-backend/Application/Interfaces/IProductRepository.cs
  backend/BMT-backend/Application/Interfaces/IUserRepository.cs
  backend/BMT-backend/Application/Services/DirectionService.cs
  backend/BMT-backend/Application/Services/EnterpriseService.cs
  backend/BMT-backend/Application/Services/OrderService.cs
  backend/BMT-backend/Application/Services/ProductService.cs
  backend/BMT-backend/Application/Services/UserService.cs
  backend/BMT-backend/Domain/Entities/Direction.cs
  backend/BMT-backend/Domain/Entities/Enterprise.cs
  backend/BMT-backend/Domain/Entities/Entrepreneur.cs
  backend/BMT-backend/Infrastructure/Data/DirectionRepository.cs
  backend/BMT-backend/Infrastructure/Data/EnterpriseRepository.cs
  backend/BMT-backend/Infrastructure/Data/EntrepeneurRepository.cs
  backend/BMT-backend/Infrastructure/Data/OrderRepository.cs
  backend/BMT-backend/Infrastructure/Data/ProductRepository.cs
  backend/BMT-backend/Infrastructure/Data/UserRepository.cs
  backend/BMT-backend/Presentation/Controllers/DirectionController.cs
  backend/BMT-backend/Presentation/Controllers/EnterpriseController.cs
  backend/BMT-backend/Presentation/Controllers/EntrepreneurController.cs
  backend/BMT-backend/Presentation/Controllers/OrderController.cs
  backend/BMT-backend/Presentation/Controllers/ProductController.cs
  backend/BMT-backend/Presentation/Controllers/UserController.cs
  database/17-SoftDeleteLogic.sql
  frontend/bmt-frontend/src/components/AppSidebar.vue
  frontend/bmt-frontend/src/components/EnterpriseInventory.vue
  frontend/bmt-frontend/src/components/EntrepreneurRegisteredEnterprises.vue
  frontend/bmt-frontend/src/components/UserDeleteConfirmation.vue
  frontend/bmt-frontend/src/components/UserProfilePage.vue
  frontend/bmt-frontend/src/main.js
Labels: bug

#68 Canceled order reports
  backend/BMT-Unit-Tests/CanceledOrdersReport.cs
  backend/BMT-backend/Application/Interfaces/IOrderRepository.cs
  backend/BMT-backend/Application/Services/OrderService.cs
  backend/BMT-backend/Domain/Entities/Order.cs
  backend/BMT-backend/Infrastructure/Data/OrderRepository.cs
  backend/BMT-backend/Infrastructure/MailService.cs
  backend/BMT-backend/Presentation/Controllers/DeveloperController.cs
  backend/BMT-backend/Presentation/Controllers/UserController.cs
  backend/BMT-backend/Presentation/DTOs/ReportDto.cs
  database/20_AlterTriggerNumOrder.sql
  frontend/bmt-frontend/src/components/OrdersReports.vue
Labels: documentation, enhancement, good first issue

#70 Dashboard de emprendedores y de administradores de sistema
  backend/BMT-Unit-Tests/DistanceCalculatorTest.cs
  backend/BMT-Unit-Tests/UserValidationTest.cs
  backend/BMT-backend/Application/Interfaces/IOrderRepository.cs
  backend/BMT-backend/Application/Queries/GetAllEnterprisesEarningsQuery.cs
  backend/BMT-backend/Application/Queries/GetEnterpriseEarningsQuery.cs
  backend/BMT-backend/Application/Queries/GetSystemTotalDeliveryFeeQuery.cs
  backend/BMT-backend/Application/Queries/SearchProductsAndEnterprisesQuery.cs
  backend/BMT-backend/Application/Services/DistanceCalculator.cs
  backend/BMT-backend/Application/Services/EnterpriseService.cs
  backend/BMT-backend/Application/Services/OrderService.cs
  backend/BMT-backend/Infrastructure/Data/OrderRepository.cs
  backend/BMT-backend/Infrastructure/Data/ProductRepository.cs
  backend/BMT-backend/Presentation/Controllers/DeveloperController.cs
  backend/BMT-backend/Presentation/Controllers/EnterpriseController.cs
  backend/BMT-backend/Presentation/Controllers/OrderController.cs
  backend/BMT-backend/Presentation/Controllers/SearchController.cs
  backend/BMT-backend/Presentation/DTOs/EarningsDatasetDto.cs
  backend/BMT-backend/Program.cs
  database/19_FullTextSearchQuery.sql
  frontend/bmt-frontend/package-lock.json
  frontend/bmt-frontend/package.json
  frontend/bmt-frontend/src/components/AppFooter.vue
  frontend/bmt-frontend/src/components/AppSidebar.vue
  frontend/bmt-frontend/src/components/CheckOut.vue
  frontend/bmt-frontend/src/components/DeveloperDashboard.vue
  frontend/bmt-frontend/src/components/EnterpriseDashboard.vue
  frontend/bmt-frontend/src/components/EntrepreneurRegisteredEnterprises.vue
  frontend/bmt-frontend/src/components/HomePage.vue
  frontend/bmt-frontend/src/components/LineChart.vue
  frontend/bmt-frontend/src/components/PendingOrders.vue
  frontend/bmt-frontend/src/components/ProductCard.vue
  frontend/bmt-frontend/src/components/RedirectionerPage.vue
  frontend/bmt-frontend/src/components/StackedBarChart.vue
  frontend/bmt-frontend/src/components/UserDashboard.vue
  frontend/bmt-frontend/src/components/UserShoppingCart.vue
  frontend/bmt-frontend/src/main.js
Labels: enhancement

#71 Merge request de las correcciones de los resúmenes de developer
  backend/BMT-backend/Application/Services/EnterpriseService.cs
  backend/BMT-backend/Application/Services/ProductService.cs
  backend/BMT-backend/Application/Services/UserService.cs
  backend/BMT-backend/Infrastructure/Data/EnterpriseRepository.cs
  backend/BMT-backend/Infrastructure/Data/ProductRepository.cs
  backend/BMT-backend/Infrastructure/Data/UserRepository.cs
  backend/BMT-backend/Presentation/Controllers/DeveloperController.cs
  backend/BMT-backend/Presentation/DTOs/EnterpriseDevDto.cs
  backend/BMT-backend/Presentation/DTOs/ProductDevDto.cs
  backend/BMT-backend/Presentation/DTOs/UserDevDto.cs
  frontend/bmt-frontend/src/components/DeveloperEnterprises.vue
  frontend/bmt-frontend/src/components/DeveloperProducts.vue
  frontend/bmt-frontend/src/components/DeveloperUsers.vue
Labels: documentation, enhancement, good first issue

#72 Register login
  backend/BMT-backend/Application/Services/OrderService.cs
  backend/BMT-backend/Presentation/DTOs/ReportDto.cs
  frontend/bmt-frontend/src/components/AppHeader.vue
  frontend/bmt-frontend/src/components/AppSidebar.vue
  frontend/bmt-frontend/src/components/DeveloperEnterprises.vue
  frontend/bmt-frontend/src/components/DeveloperUsers.vue
  frontend/bmt-frontend/src/components/EnterpriseRegisterForm.vue
  frontend/bmt-frontend/src/components/OrdersReports.vue
  frontend/bmt-frontend/src/components/ProductCard.vue
  frontend/bmt-frontend/src/components/ReportsDashboard.vue
  frontend/bmt-frontend/src/components/ReportsTable.vue
  frontend/bmt-frontend/src/components/UserEmailVerification.vue
  frontend/bmt-frontend/src/components/UserLoginForm.vue
  frontend/bmt-frontend/src/components/UserRegisterForm.vue
  frontend/bmt-frontend/src/components/YearlyEarnings.vue
Labels: documentation, enhancement, good first issue

#73 Creación de gráficos semanales
  backend/BMT-backend/Application/Interfaces/IOrderRepository.cs
  backend/BMT-backend/Application/Queries/GetEnterpriseWeeklyEarningsQuery.cs
  backend/BMT-backend/Infrastructure/Data/OrderRepository.cs
  backend/BMT-backend/Presentation/Controllers/DeveloperController.cs
  backend/BMT-backend/Presentation/Controllers/EnterpriseController.cs
  backend/BMT-backend/Program.cs
  frontend/bmt-frontend/src/components/AppSidebar.vue
  frontend/bmt-frontend/src/components/DeveloperDashboard.vue
  frontend/bmt-frontend/src/components/EnterpriseDashboard.vue
  frontend/bmt-frontend/src/components/StackedBarChart.vue
  frontend/bmt-frontend/src/components/UserDeleteConfirmation.vue
  frontend/bmt-frontend/src/components/UserProfilePage.vue
Labels: enhancement

#74 UI testing
  backend/BMT-UITesting/BMTUITesting.csproj
  backend/BMT-UITesting/LoginUITest.cs
  backend/BMT-backend/BMT-backend.sln
  frontend/bmt-frontend/src/components/AppHeader.vue
  frontend/bmt-frontend/src/components/UserLoginForm.vue
Labels: enhancement
